In [1]:
import pandas as pd
import json
import os

dirPath = 'TwiBot-22/'
comPath = dirPath + 'sub-communities/'

In [2]:
os.listdir(comPath)

['user6.json',
 'user7.json',
 'user0.json',
 'user1.json',
 'user2.json',
 'user3.json',
 'user8.json',
 'user4.json',
 'user5.json',
 'user9.json']

In [3]:
with open(comPath + 'user0.json') as f:
    userList = json.load(f)
len(userList)

10000

In [4]:
dfEdge = pd.read_csv(dirPath + 'edge.csv')
dfEdge

                      source_id    relation             target_id
0           u980749991491682304   followers  u1480979504696864775
1                    u105387876   following            u402576793
2                    u148520716   following             u59653593
3          u1276438425457967110   following  u1389155636693381120
4          u1445432327367237638   following   u848348952084828160
...                         ...         ...                   ...
170185932             l40863046  membership              u1879831
170185933            l108800322  membership             u38142665
170185934   l994265798876303362  membership             u17759387
170185935             l82138286  membership            u932805374
170185936             l14790163  membership             u24940652

[170185937 rows x 3 columns]

In [6]:
dfPart = dfEdge.loc[(dfEdge['source_id'].isin(userList)) & (dfEdge['target_id'].isin(userList))]
dfPart

                    source_id   relation             target_id
20974                u7202792  followers             u48569551
29160    u1140206472615333893  following           u1567846093
44459               u20674741  following             u62588600
74675               u20657343  following             u16129920
84826               u66560735  following             u17713899
...                       ...        ...                   ...
3689453   u755122072095977473  following  u1095834875716874245
3699658  u1409043813943943172  following            u117027524
3701320  u1357351456387592195  followers   u959835096105840640
3731843           u4021650673  following            u937499232
3743173             u20674741  following            u937499232

[325 rows x 3 columns]

In [7]:
for i in range(1, 10):
    with open(comPath + 'user' + str(i) + '.json') as f:
        userList = json.load(f)
    df = dfEdge.loc[(dfEdge['source_id'].isin(userList)) & (dfEdge['target_id'].isin(userList))]
    print('community', i)
    print(df)

community 1
                    source_id   relation             target_id
113      u1002287910064934917  following             u41314673
3449                u26304269  following             u42934860
14626              u635334644  following             u11581462
23857              u635826578  following  u1101154293283991553
24968              u635334644  following              u6902372
...                       ...        ...                   ...
3727186             u57497901  following  u1422402274236665858
3728941           u1124405762  followers  u1179273321705197568
3729897           u2273216286  following   u933456017039298561
3737934   u802615428711268352  followers            u512275659
3738252   u739133515170729984  followers             u32723833

[780 rows x 3 columns]
community 2
                    source_id   relation             target_id
2290              u1903560060  followers            u299264437
9838               u192589318  following           u1446376116
14417             u1903560060  following           u3874485862
19006     u904523130919628801  following            u307683779
19635              u547871798  followers  u1271048434330537985
...                       ...        ...                   ...
3730886  u1016359279895474176  followers   u979585694711521281
3738870            u863348545  following            u137198738
3743227             u53096584  following             u36058028
3743394  u1389961515705454597  followers             u95869205
3743472   u879663599815467008  following             u14108472

[872 rows x 3 columns]
community 3
                    source_id   relation             target_id
10039              u593658151  followers   u852577770085502976
20423    u1233194297928933377  followers           u2789007754
22550     u714447618777202688  following  u1349296819633872896
26729              u445439525  following            u387156826
28626     u781982295863484456  followers  u1249411338218037248
...                       ...        ...                   ...
3730188            u225895485  following            u387156826
3737535             u67949052  followers             u14486697
3738738           u3915253634  followers  u1353091575425986560
3740491  u1376841165937520641  following            u271697941
3742575  u1005087744027082752  following   u719037126621270016

[687 rows x 3 columns]
community 4
                    source_id   relation             target_id
8595              u4702650451  followers             u17536486
16003     u863090413640572930  following            u301750247
22641              u419037620  following  u1154031225394253825
28535              u122037755  following   u834609484781723648
29058              u135218064  following            u181245414
...                       ...        ...                   ...
3726135            u929741558  followers            u483847415
3733718  u1041440667313078274  followers              u6011782
3733792            u394095128  followers           u1115509724
3735272   u855742402950287361  following   u819281746806054912
3737327            u382020443  followers            u181245414

[606 rows x 3 columns]
community 5
                    source_id   relation             target_id
3588               u279165077  following             u17839644
3705                    u5413  following             u74872238
3895      u968396033918230528  following             u16196307
5378               u728709530  following            u230206137
6334               u836314434  following   u731538535795163136
...                       ...        ...                   ...
3733017           u3248845414  following             u15426691
3734157  u1479883426895478784  following  u1206525903318265856
3737552   u703640251378618369  following            u743856512
3738223            u855714950  following             u76875399
3741783             u15084892  followers             u59232196

[3401 rows x 3 columns]
community 6
                    source_id   relation             target_id
475               u3473022974  followers           u2688973478
1117              u1897970054  followers  u1285134035946266624
1408     u1054715013942951936  following            u605573599
1667     u1422891345300045826  following  u1336601017262112771
1966     u1462278983182082048  following  u1338994562090602497
...                       ...        ...                   ...
3742290           u1583338284  following             u15647676
3742782              u8612022  following  u1158412476456812544
3742869            u929211084  followers           u1365309446
3742977  u1269068431862763525  following  u1265121374575583232
3743019  u1156564906289881091  followers  u1112742948779622403

[9069 rows x 3 columns]
community 7
                    source_id   relation             target_id
2554      u876895425835479041  following             u41148474
3857                u15338284  following           u3379658705
6909               u905399486  followers             u56168599
7411               u148639030  following  u1373472847750893569
12996              u139598778  following   u797738947564564480
...                       ...        ...                   ...
3736466  u1005616619316482049  following            u613491958
3738082             u54034504  following            u166739404
3740304            u220364966  following           u4657465878
3742287             u18885806  following           u2344530218
3742898   u876895425835479041  following  u1136738117505826816

[3163 rows x 3 columns]
community 8
                    source_id   relation             target_id
1047                u90361778  following  u1124432439194062848
1344               u119837224  following           u2255642364
1471      u783808494470168577  following           u1282121312
1563                u19405351  following           u2688930078
1689     u1278390703320715264  following             u18082365
...                       ...        ...                   ...
3734467            u251758893  followers           u1162900004
3737852             u31404872  following   u999945589260537856
3738515           u3099560412  followers  u1378448473205272578
3740577  u1148997425912262656  following   u705709976501817348
3741799  u1397958034652082176  followers  u1245136726626119687

[2893 rows x 3 columns]
community 9
                    source_id   relation             target_id
113      u1002287910064934917  following             u41314673
147               u3292745711  following             u42208855
323                 u16232185  followers  u1136617467151814657
2922               u984219792  following  u1378776755738140675
4362               u266889634  following              u4519121
...                       ...        ...                   ...
3736716           u3169963433  following   u764062320553234433
3738618           u1544468570  followers           u2938395862
3741935   u908449352913506304  followers            u182016771
3742569             u53919551  following            u520445177
3743441           u2238505946  followers  u1125553711948926978

[3362 rows x 3 columns]

In [8]:
# 直接在following关系上跑社区发现算法看看能不能抽取出比较好的社区？
dfFollow = pd.read_csv(dirPath + 'edge_following.csv')
dfFollow

                    source_id   relation             target_id
0                  u105387876  following            u402576793
1                  u148520716  following             u59653593
2        u1276438425457967110  following  u1389155636693381120
3        u1445432327367237638  following   u848348952084828160
4        u1445432327367237638  following   u850507814023942144
...                       ...        ...                   ...
2626974             u27771694  following             u76691299
2626975            u169038927  following           u1047788701
2626976   u905264066255613952  following   u831248331800190976
2626977   u786332275755458560  following           u1376582724
2626978  u1458510589580427276  following            u553753344

[2626979 rows x 3 columns]

In [10]:
dfFollowing = dfFollow
dfFollower = pd.read_csv(dirPath + 'edge_followers.csv')
dfFollower

                    source_id   relation             target_id
0         u980749991491682304  followers  u1480979504696864775
1                 u2704715387  followers  u1483909830159085571
2         u753165526566899713  followers           u1484420078
3                  u114820052  followers             u18876842
4                 u1924484352  followers           u3408319427
...                       ...        ...                   ...
1116650  u1419703898563035142  followers  u1181886724609323008
1116651  u1409555675139686406  followers   u739740881134202880
1116652           u2287991321  followers           u3232262080
1116653           u1665665700  followers  u1225421792845672450
1116654           u1387514922  followers   u870408205679042560

[1116655 rows x 3 columns]

In [11]:
def nodeMap(userSet):
    mapping = {i: index for index, i in enumerate(userSet)}
    return mapping

In [12]:
userSet = set(dfFollowing['source_id'].tolist()) | set(dfFollowing['target_id'].tolist())
len(userSet)

530297

In [13]:
userSet1 = set(dfFollower['source_id'].tolist()) | set(dfFollower['target_id'].tolist())
len(userSet1)

433645

In [14]:
userMap = nodeMap(userSet)

In [16]:
userMap['u105387876']

22407

In [17]:
dfFollowing['sid'] = dfFollowing['source_id'].map(userMap)
dfFollowing['tid'] = dfFollowing['target_id'].map(userMap)
dfFollowing

                    source_id   relation             target_id     sid     tid
0                  u105387876  following            u402576793   22407  391898
1                  u148520716  following             u59653593   92499  504624
2        u1276438425457967110  following  u1389155636693381120  247526  517088
3        u1445432327367237638  following   u848348952084828160  282611  385444
4        u1445432327367237638  following   u850507814023942144  282611   18007
...                       ...        ...                   ...     ...     ...
2626974             u27771694  following             u76691299  243838  441787
2626975            u169038927  following           u1047788701  131037   83738
2626976   u905264066255613952  following   u831248331800190976  182750  230968
2626977   u786332275755458560  following           u1376582724  478834  188395
2626978  u1458510589580427276  following            u553753344  200731   63430

[2626979 rows x 5 columns]

In [19]:
import networkx as nx
GFollowing = nx.from_pandas_edgelist(dfFollowing, 'sid', 'tid')

In [20]:
from networkx.algorithms import community
louvainCom = community.louvain_communities(GFollowing)

In [21]:
lovainCom = sorted(louvainCom, key=len, reverse=True)

In [22]:
len(lovainCom)

72

In [25]:
with open(dirPath + 'allBotListID.json') as f:
    botList = json.load(f)
len(botList)

139943

In [26]:
botPart = set(botList) & userSet
len(botPart)

45208

In [27]:
botID = list([userMap[bot] for bot in botPart])
len(botID)

45208

In [28]:
botID = set(botID)

In [31]:
for com in lovainCom[:20]:
    a = len(com)
    b = len(com & botID)
    print(a, b, b/a)

89982 5001 0.055577782223111286
71184 8812 0.12379186334007643
65627 6286 0.09578374754293202
52798 6676 0.12644418349179892
48238 3102 0.06430614867946433
42179 2669 0.0632779345171768
37400 3241 0.08665775401069518
27882 1488 0.053367764148913276
21842 2170 0.09934987638494644
15699 574 0.03656283839735015
10019 535 0.05339854276873939
8694 981 0.11283643892339544
7680 562 0.07317708333333334
5332 723 0.13559639909977494
5134 389 0.07576938059992208
3879 367 0.09461201340551689
3634 193 0.053109521188772706
2908 320 0.11004126547455295
2734 239 0.08741770299926847
1861 84 0.045137023105857065

In [33]:
dfFollowerPart = dfFollower.loc[(dfFollower['source_id'].isin(userSet)) & (dfFollower['target_id'].isin(userSet))]
dfFollowerPart

                    source_id   relation             target_id
3                  u114820052  followers             u18876842
5                    u5932762  followers  u1005804188238934017
6                    u5932762  followers  u1030960674032119809
7                    u5932762  followers   u963065581439086593
8                   u18783525  followers             u17583795
...                       ...        ...                   ...
1116649           u3290526443  followers           u1885420650
1116650  u1419703898563035142  followers  u1181886724609323008
1116651  u1409555675139686406  followers   u739740881134202880
1116652           u2287991321  followers           u3232262080
1116653           u1665665700  followers  u1225421792845672450

[847461 rows x 3 columns]

In [34]:
com11 = lovainCom[11]
len(com11)

8694

In [35]:
dfFollowerPart['sid'] = dfFollowerPart['source_id'].map(userMap)
dfFollowerPart['tid'] = dfFollowerPart['target_id'].map(userMap)
dfFollowerPart

/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_31322/2965349452.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfFollowerPart['sid'] = dfFollowerPart['source_id'].map(userMap)
/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_31322/2965349452.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfFollowerPart['tid'] = dfFollowerPart['target_id'].map(userMap)

                    source_id   relation             target_id     sid     tid
3                  u114820052  followers             u18876842  248722  178911
5                    u5932762  followers  u1005804188238934017  524959  219581
6                    u5932762  followers  u1030960674032119809  524959    6712
7                    u5932762  followers   u963065581439086593  524959  403794
8                   u18783525  followers             u17583795  450050  108966
...                       ...        ...                   ...     ...     ...
1116649           u3290526443  followers           u1885420650  341231  450517
1116650  u1419703898563035142  followers  u1181886724609323008  307536  526314
1116651  u1409555675139686406  followers   u739740881134202880  285391  309499
1116652           u2287991321  followers           u3232262080  468451  196587
1116653           u1665665700  followers  u1225421792845672450  435605  146352

[847461 rows x 5 columns]

In [36]:
dfFollowerPart.loc[(dfFollowerPart['sid'].isin(com11)) & (dfFollowerPart['tid'].isin(com11))]

                    source_id   relation             target_id     sid     tid
275      u1129880305442017280  followers  u1246253178984624128   37506  424211
335       u851193949494628352  followers   u874396352318492672  217393  402956
736      u1232290896508485634  followers           u2465436362  485938  312092
1006     u1129880305442017280  followers  u1308966317886705665   37506  176315
1344              u4920409179  followers   u887969633952780289  144392  168004
...                       ...        ...                   ...     ...     ...
1113132           u4920409179  followers           u1599552121  144392  471162
1113510  u1311808795509583872  followers  u1387607551362039811  266529  438257
1114786  u1016786527748313088  followers  u1321877453070082049   75798   59484
1115098           u2935178708  followers            u131116588  250394  256734
1115626  u1290994327502503936  followers  u1317454355247759361  204936  318832

[3855 rows x 5 columns]

In [37]:
dfFollowing.loc[(dfFollowing['sid'].isin(com11)) & (dfFollowing['tid'].isin(com11))]

                    source_id   relation             target_id     sid     tid
57       u1012124895088726016  following           u1599552121   16912  471162
261                u152731757  following             u30026226  414890  373414
286                u799145528  following           u2397208592  340446    9193
315                u902120672  following            u225189569   29008    9633
326                u799145528  following  u1108640256474132480  340446    5646
...                       ...        ...                   ...     ...     ...
2625564           u1201410884  following           u3268969388  196681   61953
2625719             u51354433  following            u253244964  526861  155259
2625804            u224332668  following            u527856001  307084  262752
2626644            u305213013  following   u730275307534553088  430394  228140
2626827            u206132942  following            u344622950  132067  460897

[13504 rows x 5 columns]

In [38]:
userReMap = {i:user for user, i in userMap.items()}
userReMap[1]

'u2848586255'

In [39]:
userMap['u2848586255']

1

In [40]:
uidCom = list([userReMap[i] for i in com11])
uidCom[:10]

['u1248526327193522177',
 'u333021825',
 'u50051483',
 'u1328324103565053957',
 'u942875259182702592',
 'u557150982',
 'u410904318',
 'u3244877951',
 'u833103863007870978',
 'u1390297140128219142']

In [41]:
len(uidCom)

8694

In [42]:
tidList = dfEdge.loc[(dfEdge['relation'] == 'post') & (dfEdge['source_id'].isin(uidCom))]['target_id']

In [43]:
tidList = tidList.tolist()
len(tidList)

984717

In [44]:
set(dfEdge['relation'].tolist())

{'contain',
 'discuss',
 'followed',
 'followers',
 'following',
 'like',
 'membership',
 'mentioned',
 'own',
 'pinned',
 'post',
 'quoted',
 'replied_to',
 'retweeted'}

In [45]:
tweetRelas = ['quoted', 'replied_to', 'retweeted']
dfTweet = dfEdge.loc[(dfEdge['relation'].isin(tweetRelas)) & 
                     (dfEdge['source_id'].isin(tidList)) & (dfEdge['target_id'].isin(tidList))]
dfTweet

                      source_id    relation             target_id
166178251  t1268274950907015168  replied_to  t1268161763138297858
166178279  t1427342075205341191   retweeted  t1427341204509835264
166178306  t1412726752959512577  replied_to  t1412726751961223168
166178344  t1483511703258435584  replied_to  t1483505495168143370
166178448  t1491361887996768258  replied_to  t1491361116219650048
...                         ...         ...                   ...
169162836  t1263338516915859457   retweeted  t1263228699484262400
169162959  t1464800121028292611   retweeted  t1464795723900276740
169163329  t1421439998654615553   retweeted  t1421438967887585283
169163340   t506421397824880640   retweeted   t506388938915729408
169163348  t1488516374548856835  replied_to  t1488469083460976642

[25235 rows x 3 columns]

In [46]:
25235 / 8694

2.9025764895330113

In [47]:
# partPath = 'TwiBot-22-com/'

dfUser = pd.read_json(dirPath + 'user.json')
dfUser

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld
0,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,"{'followers_count': 7316, 'following_count': 2...",https://t.co/BoMip9FF17,boazbaraktcs,False,None
1,2014-07-02 17:56:46+00:00,creative _,None,u2664730894,🎈,olawale 💨,NaN,https://pbs.twimg.com/profile_images/147837638...,False,"{'followers_count': 123, 'following_count': 10...",,wale_io,False,None
2,2020-05-30 12:10:45+00:00,👽,None,u1266703520205549568,None,panagiota_.b,NaN,https://pbs.twimg.com/profile_images/142608606...,False,"{'followers_count': 3, 'following_count': 62, ...",,b_panagiota,False,None
3,2019-01-26 13:52:49+00:00,mama to maya. ABIM research pathway fellow @UV...,"{'description': {'mentions': [{'start': 43, 'e...",u1089159225148882949,"Charlottesville, VA","Jacqueline Hodges, MD MPH",NaN,https://pbs.twimg.com/profile_images/130229171...,False,"{'followers_count': 350, 'following_count': 57...",,jachodges_md,False,None
4,2009-04-30 19:01:42+00:00,Father / SWT Alumnus / Longhorn Fan,None,u36741729,United States,Matthew Stubblefield,NaN,https://pbs.twimg.com/profile_images/145808462...,True,"{'followers_count': 240, 'following_count': 29...",,Matthew_Brody,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2013-02-05 14:50:17+00:00,イラストACは高品質イラストアート/年賀状等が全無料DL可能♪AIベクター・EPS形式素材全...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1151138281,↓利用者600万人無料素材サイト↓ 商用利用編集ＯＫ表記不要,フリー素材集かわいい無料イラストAC/おしゃれフレーム枠★IllustACイラストレーター,1.301109e+18,https://pbs.twimg.com/profile_images/139750409...,False,"{'followers_count': 1877, 'following_count': 2...",https://t.co/L6PE11Blkl,Illustratorjpn,False,None
999996,2013-04-09 12:09:34+00:00,next➬未定 紫･緑ﾃﾞｨｯｷ 色々な曲聴きます,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1339035361,OKAYAMA CITY,りょうやん,6.067787e+17,https://pbs.twimg.com/profile_images/135842413...,False,"{'followers_count': 13952, 'following_count': ...",https://t.co/NjDtATyqGc,_y3oa,False,None
999997,2011-06-16 20:09:29+00:00,Heart of a lion with a Mind of a maniac. Louis...,None,u318636852,"Lake Charles, LA",Gavin Cecchini,NaN,https://pbs.twimg.com/profile_images/781352355...,False,"{'followers_count': 13743, 'following_count': ...",,GavinCecchini2,True,None
999998,2009-05-30 00:25:19+00:00,"Marketplace Minister, Christ follower, Indepen...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u43443354,Rockhampton Australia,Martin Allan,NaN,https://pbs.twimg.com/profile_images/131699997...,False,"{'followers_count': 2460, 'following_count': 2...",https://t.co/r3R5Bkng9m,MartinfromOz,False,None
999999,2009-04-07 15:33:46+00:00,I'm a CELEBRITY make up artist wanting every w...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u29471345,"Philadephia,PA",Tiffany/Beauty Mark,NaN,https://pbs.twimg.com/profile_images/111165686...,False,"{'followers_count': 471, 'following_count': 52...",https://t.co/N0wEYcP0ud,Makeupbytiffy,False,None

In [48]:
dfUserPart = dfUser.loc[dfUser['id'].isin(uidCom)]
dfUserPart

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld
52,2016-09-02 17:13:51+00:00,‏‏‏Abdelwahed Wajih\nعبدالواحد وجيه,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u771758047412748288,None,عبد الواحد وجيه,NaN,https://pbs.twimg.com/profile_images/771764768...,False,"{'followers_count': 2461, 'following_count': 2...",https://t.co/Wev6rydYcI,Wajihabdelwahd0,False,None
92,2009-10-29 08:21:28+00:00,Try my best in all my way to life happily..,None,u86020763,Indonesia,bernardinus,NaN,https://pbs.twimg.com/profile_images/349683458...,False,"{'followers_count': 93, 'following_count': 98,...",,Nduzzt,False,None
111,2018-06-06 19:11:31+00:00,waiting......2022⭐⭐,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1004440668763230210,"El Qaliobia, Egypt",Alhassan,NaN,https://pbs.twimg.com/profile_images/145774969...,False,"{'followers_count': 61, 'following_count': 139...",https://t.co/yuALOjMusA,Alhassa13553164,False,None
235,2014-05-25 14:02:22+00:00,#Bugdroidy #FCIS #Barca,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u2522772534,"Cairo, Egypt",khaled sherif,NaN,https://pbs.twimg.com/profile_images/123885339...,False,"{'followers_count': 287, 'following_count': 31...",https://t.co/0omT0uNzyZ,Meslmawy,False,None
266,2021-03-25 15:48:41+00:00,رب الخير لا ياتى إلا بالخير 🖤,None,u1375112149157216258,None,Nada Abd Alrhman,NaN,https://pbs.twimg.com/profile_images/145660076...,False,"{'followers_count': 39, 'following_count': 141...",,NadaAbdAlrhman3,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531878,2020-05-04 19:20:34+00:00,"egyptian illustrator, comic artist, and magica...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1257389639318585345,20 | she/her,✨Nour T✨ COMMISSIONS OPEN,1.428708e+18,https://pbs.twimg.com/profile_images/147849174...,False,"{'followers_count': 1773, 'following_count': 1...",https://t.co/SAFo4cnBOF,nourtarts,False,None
531879,2020-05-18 02:15:44+00:00,irgendwie irgendwo irgendwann.,None,u1262205160983605250,None,Dwight,NaN,https://pbs.twimg.com/profile_images/136715285...,False,"{'followers_count': 5542, 'following_count': 4...",,dewheit,False,None
531880,2011-10-26 19:01:06+00:00,‏‏الراعي الرسمي لتايم لاين الانمي,None,u398927679,Laugh Tale,الكايزوكو اوني والناكاما بتوعه 🤓,1.231680e+18,https://pbs.twimg.com/profile_images/148066499...,False,"{'followers_count': 3544, 'following_count': 2...",,_AhmedYehya_,False,None
531881,2008-05-20 16:07:04+00:00,"Founder and CEO, 👕🚀\nSports and Gaming\n\nForm...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u14846901,"Dallas, TX",Chris Chaney marcaurel.eth 🇩🇪🇺🇸,NaN,https://pbs.twimg.com/profile_images/126828321...,False,"{'followers_count': 1720, 'following_count': 7...",https://t.co/VGxZ1Wvm5g,chrischaney,False,None
531882,2009-03-25 12:57:54+00:00,"Marvel comics writer: X-FACTOR, GWENPOOL STRIK...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u26490474,"the boneyard, krakoa",Leah Williams,NaN,https://pbs.twimg.com/profile_images/882723937...,False,"{'followers_count': 23119, 'following_count': ...",https://t.co/zk3zXHEC5i,mymonsterischic,False,None

In [80]:
partPath = 'TwiBot-22-com/'
dfUserPart.to_json(partPath + 'user.json')

In [50]:
dfUserEdge = dfEdge.loc[(dfEdge['source_id'].isin(uidCom)) & (dfEdge['target_id'].isin(uidCom))]
dfUserEdge

                    source_id   relation             target_id
79       u1012124895088726016  following           u1599552121
371                u152731757  following             u30026226
405                u799145528  following           u2397208592
451                u902120672  following            u225189569
462                u799145528  following  u1108640256474132480
...                       ...        ...                   ...
3741596           u1201410884  following           u3268969388
3741824             u51354433  following            u253244964
3741958            u224332668  following            u527856001
3743155            u305213013  following   u730275307534553088
3743424            u206132942  following            u344622950

[17359 rows x 3 columns]

In [51]:
dfPost = dfEdge.loc[(dfEdge['relation'] == 'post') & dfEdge['source_id'].isin(uidCom)]
dfPost

                     source_id relation             target_id
4112709             u904794157     post  t1499039530996879361
4112780            u1056701298     post  t1498387236869574666
4112860              u17659206     post  t1495279793654603776
4113004            u1321294374     post  t1346994483603386368
4113086            u3248066106     post  t1499420340350562306
...                        ...      ...                   ...
92329663  u1355108554223579138     post  t1491915062327619586
92329685  u1062757951830679557     post  t1414287286607433739
92329711  u1243520404754321408     post  t1491797920697700353
92329874            u135446697     post  t1485540714461159424
92330018             u22413122     post  t1495755772306800642

[984717 rows x 3 columns]

In [52]:
dfPartAll = pd.concat([dfUserEdge, dfPost, dfTweet], ignore_index=True)
dfPartAll

                    source_id    relation             target_id
0        u1012124895088726016   following           u1599552121
1                  u152731757   following             u30026226
2                  u799145528   following           u2397208592
3                  u902120672   following            u225189569
4                  u799145528   following  u1108640256474132480
...                       ...         ...                   ...
1027306  t1263338516915859457   retweeted  t1263228699484262400
1027307  t1464800121028292611   retweeted  t1464795723900276740
1027308  t1421439998654615553   retweeted  t1421438967887585283
1027309   t506421397824880640   retweeted   t506388938915729408
1027310  t1488516374548856835  replied_to  t1488469083460976642

[1027311 rows x 3 columns]

In [53]:
relaAll = dfPartAll['relation'].tolist()
for rela in set(relaAll):
    print(rela, relaAll.count(rela))

quoted 1485
retweeted 11541
replied_to 12209
followers 3855
following 13504
post 984717

In [54]:
dfPartAll.to_csv(partPath + 'edge.csv', index=False)

In [55]:
dfSplit = pd.read_csv(dirPath + 'split.csv')

In [56]:
dfSplitPart = dfSplit.loc[dfSplit['id'].isin(uidCom)]
dfSplitPart

                          id  split
37       u771758047412748288  train
198     u1118067018035449856  train
228               u145169990  train
231               u148390293  train
264                u17659206  train
...                      ...    ...
947248   u769874289835343872   test
947249  u1101206378096611330   test
948070  u1237441256017596416   test
949229  u1475199988124712962   test
949230           u3243052292   test

[8694 rows x 2 columns]

In [57]:
splitListPart = dfSplitPart['split'].to_list()
for label in set(splitListPart):
    print(label, splitListPart.count(label))

test 747
val 1658
train 6289

In [58]:
dfUidPart = dfUser.loc[dfUser['id'].isin(uidCom)]['id']
dfUidPart

52         u771758047412748288
92                   u86020763
111       u1004440668763230210
235                u2522772534
266       u1375112149157216258
                  ...
531878    u1257389639318585345
531879    u1262205160983605250
531880              u398927679
531881               u14846901
531882               u26490474
Name: id, Length: 8694, dtype: object

In [60]:
dfSplitPart['split'] = 'test'

/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_31322/4086601852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSplitPart['split'] = 'test'

In [61]:
dfSplitPart

                          id split
37       u771758047412748288  test
198     u1118067018035449856  test
228               u145169990  test
231               u148390293  test
264                u17659206  test
...                      ...   ...
947248   u769874289835343872  test
947249  u1101206378096611330  test
948070  u1237441256017596416  test
949229  u1475199988124712962  test
949230           u3243052292  test

[8694 rows x 2 columns]

In [63]:
dfSplitPart.sample(frac=0.7, random_state=1)['split'] = 'train'
dfSplitPart

                          id split
37       u771758047412748288  test
198     u1118067018035449856  test
228               u145169990  test
231               u148390293  test
264                u17659206  test
...                      ...   ...
947248   u769874289835343872  test
947249  u1101206378096611330  test
948070  u1237441256017596416  test
949229  u1475199988124712962  test
949230           u3243052292  test

[8694 rows x 2 columns]

In [67]:
# 生成一个随机的list直接给目标赋值
import random

In [68]:
random.seed(4)

In [70]:
randList = ['test'] * 869 + ['val'] * 869 * 2 + ['train'] * int(8694 - 869 * 3)
len(randList)

8694

In [72]:
random.shuffle(randList)

In [73]:
randList[0]

'train'

In [74]:
for r in ['test', 'val', 'train']:
    print(r, randList.count(r))

test 869
val 1738
train 6087

In [75]:
dfSplitPart['split'] = randList

/var/folders/pk/9j79n0j97l96355kp67lwjxr0000gn/T/ipykernel_31322/2597831571.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfSplitPart['split'] = randList

In [76]:
dfSplitPart

                          id  split
37       u771758047412748288  train
198     u1118067018035449856  train
228               u145169990  train
231               u148390293  train
264                u17659206  train
...                      ...    ...
947248   u769874289835343872  train
947249  u1101206378096611330  train
948070  u1237441256017596416    val
949229  u1475199988124712962  train
949230           u3243052292  train

[8694 rows x 2 columns]

In [77]:
splitListPart = dfSplitPart['split'].to_list()
for label in set(splitListPart):
    print(label, splitListPart.count(label))

test 869
val 1738
train 6087

In [78]:
dfSplitPart.to_csv(partPath + 'split.csv', index=False)

In [81]:
with open(dirPath + 'id_tweet.json') as f:
    dictTweet = json.load(f)

In [82]:
indexList = list(dfUserPart.index)

In [83]:
dictIDPart = {str(id0): dictTweet[str(id0)] for id0 in indexList}

In [84]:
# remapping
dfUserPart = dfUserPart.reset_index(drop=True)
dfUserPart.to_json(partPath + 'user.json')

In [85]:
len(indexList)

8694

In [86]:
dictReset = {str(i) : dictIDPart[str(indexList[i])] for i in range(len(indexList))}

In [87]:
dictReset['0']

['عبدالواحد وجيه: مكانة المرأة في الإسلام https://t.co/CN0LLEhOPj',
 'عبدالواحد وجيه : أقسام الوحي https://t.co/Z4dQu41487',
 '@fahaddsalsabah اخي و صديقي الشيخ فهد دعيج الصباح اشتقت لكم كثيرا حفظكم الله أينما كنتم وسائر الأسرة الكريمة 🌷',
 'RT @hespress: كنت سبيلا في لم شمل لشعوب غدت متقطعات، لحق أنت إحدى المعجزات.. الدكتور عبد الواحد وجيه يلقي قصيدة في رثاء الطفل ريان\n#الطفل_ر…',
 '@MohammedAloui04 حفظكم الله اخي لعزيز',
 '@Sefrioui2018 بارك الله فيك أخي سعيد وجزاك الله خيرا',
 'عبدالواحد وجيه : إبراهيم عليه السلام https://t.co/d6nwnnKT36',
 'جزء من قصة نوح عليه السلام https://t.co/zxMzZhggem',
 'أمة محمد صلى الله عليه وسلم https://t.co/BA9gbBtaDM',
 '@20ghjri وعليكم السلام ورحمة الله وبركاته بارك الله فيك وجزاكم الله خيرا اسأل الله ان يحفظكم من كل سوء إن شاء لله',
 '@MohammedAlharg1 الله يحفظك ويبارك فيك إن شاء الله اخي محمد',
 'عبدالواحد وجيه: تعريف الأمية https://t.co/FZ5BiCCSCa',
 '@M5zAEdtHw2bICmv بارك الله فيك أخي لعزيز جزاك الله خيرا حفظك الله من كل سوء إن شاء الله',
 'عبدالواحد وجيه: الصداقة https://t.co/tiPmKMuyKu',
 '@M5zAEdtHw2bICmv جزآك الله خيرا اخي',
 '@DrJamai بارك الله فيك أخي لعزيز',
 'مقطع من قصة موسى عليه السلام https://t.co/pTDoWvw7Uj',
 'عبدالواحد وجيه: الفرق بين الخوف و الغم https://t.co/GiDTqjcSzJ',
 '@Sofiane1070 جزآك الله خيرا اخي سفيان حفظك الله من كل سوء إن شاء الله',
 '@Sofiane1070 بارك الله فيك أخي سفيان',
 '@Boutayebabdell3 جزاك الله خيرا اخي عبدالله']

In [88]:
indexList[0]

52

In [89]:
uidCom[52]

'u1345909323675811840'

In [90]:
dfUserPart.loc[dfUserPart['id'] == uidCom[52]]

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld
4522,2021-01-04 01:46:33+00:00,▸ 𖧧 ࣪ ࣪ ͎ 𝗮𝗿𝗺𝘆 𝗲𝗻𝗴𝗲𝗻𝗲 𝗸𝗲𝗽𝟭𝗲𝗿 ⋆ Ꮺ,None,u1345909323675811840,candy store,♡,1.452985e+18,https://pbs.twimg.com/profile_images/145297962...,False,"{'followers_count': 111, 'following_count': 15...",,bbangtanluvie,False,None

In [91]:
with open(partPath + 'id_tweet.json', 'w') as f:
    f.write(json.dumps(dictReset))

In [92]:
dfLabel = pd.read_csv(dirPath + 'label.csv')
dfLabel

                          id  label
0       u1217628182611927040  human
1                u2664730894  human
2       u1266703520205549568  human
3       u1089159225148882949  human
4                  u36741729    bot
...                      ...    ...
999995           u1151138281  human
999996           u1339035361  human
999997            u318636852  human
999998             u43443354  human
999999             u29471345  human

[1000000 rows x 2 columns]

In [94]:
dfLabelPart = dfLabel.loc[dfLabel['id'].isin(uidCom)]
dfLabelPart

                          id  label
52       u771758047412748288  human
92                 u86020763  human
111     u1004440668763230210  human
235              u2522772534  human
266     u1375112149157216258    bot
...                      ...    ...
531878  u1257389639318585345  human
531879  u1262205160983605250  human
531880            u398927679  human
531881             u14846901  human
531882             u26490474  human

[8694 rows x 2 columns]

In [95]:
dfLabelPart.loc[dfLabelPart['label'] == 'bot']

                          id label
266     u1375112149157216258   bot
335     u1118067018035449856   bot
390               u145169990   bot
486               u902120672   bot
1304    u1269977265955393536   bot
...                      ...   ...
531866   u884428650178686978   bot
531872  u1080568702989492225   bot
531875  u1350892229800439813   bot
531876  u1340430145870581760   bot
531877   u855444364771942400   bot

[981 rows x 2 columns]

In [96]:
dfLabelPart.to_csv(partPath + 'label.csv', index=False)

In [97]:
len(tidList)

984717

In [98]:
tweetPath = dirPath + 'tweets/'

In [99]:
tweetStrList = []
# 可以写个循环让代码自己跑了
for i in range(0, 9):
    with open(tweetPath + 'tweet_' + str(i) + '.json') as f:
        tweetStr = f.read()
    with open(tweetPath + 'tweet_' + str(i) + '_tid.json') as f:
        tweetTidList = json.load(f)
    tweetList = tweetStr.split('"attachments":')
    tidMap = {tweetTidList[i]: tweetList[i + 1] for i in range(len(tweetTidList))}
    print('mapping over')
    # 计算tidIn
    tidInList = list(set(tweetTidList) & set(tidList))
    # 提取tidIn对应的字符串
    tidInStr = list([tidMap[t] for t in tidInList])
    # 增加在之前的list中
    print('get tweets num' + str(len(tidInStr)))
    tweetStrList += tidInStr

mapping over
get tweets num79986
mapping over
get tweets num149889
mapping over
get tweets num143943
mapping over
get tweets num142560
mapping over
get tweets num106778
mapping over
get tweets num93584
mapping over
get tweets num93903
mapping over
get tweets num92185
mapping over
get tweets num81889

In [101]:
len(tweetStrList)

984717

In [102]:
len(tidList)

984717

In [103]:
with open(tweetPath + 'tweetStrListCom11.json', 'w') as f:
    f.write(json.dumps(tweetStrList))

In [104]:
tweetStrAll = '"attachments":'.join(tweetStrList)

In [105]:
with open(partPath + 'tweet.json', 'w') as f:
    f.write(tweetStrAll)

In [106]:
dfTweet = pd.read_json(partPath + 'tweet.json')
dfTweet

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,text,withheld
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,False,"{'retweet_count': 3, 'reply_count': None, 'lik...",None,None,"<a href=""https://studio.twitter.com"" rel=""nofo...",سبقتهم دموعهم.. لاجئون أوكرانيون على الحدود ال...,None
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,False,"{'retweet_count': 327, 'reply_count': None, 'l...",None,None,"<a href=""http://twitter.com/download/android"" ...",RT @franceonu: 🗳️ The @UN General Assembly ado...,None
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,False,"{'retweet_count': 10, 'reply_count': None, 'li...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",RT @CanesTrack: More gold coming back to the 3...,None
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,False,"{'retweet_count': 2088, 'reply_count': None, '...",None,None,"<a href=""http://twitter.com/download/android"" ...",RT @TAEONYSUS_7: MY HOME ♡ (moni + mini + mini...,None
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://mobile.twitter.com"" rel=""nofo...",Product Demo Next Week – Register Today\nSenio...,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",تعريف المماطلة وأسبابها والعواقب التي تضر المص...,None
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,True,"{'retweet_count': 72, 'reply_count': None, 'li...",None,None,"<a href=""https://github.com/corbindavenport/to...",Ukraine 🇺🇦 https://t.co/vepN7rH5YU https://t.c...,None
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,False,"{'retweet_count': 1, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",I have no qualms about this. Every day childre...,None
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",@Ramahi27 🎉🎉🎉,None
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/android"" ...",الله يرحم الثورة 😀 https://t.co/MWHmZAmqeu,None

In [107]:
# 处理推文数据得到推文数据集
dfTweet['uid'] = 'u' + dfTweet['author_id'].astype(str)
dfTweet

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,text,withheld,uid
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,False,"{'retweet_count': 3, 'reply_count': None, 'lik...",None,None,"<a href=""https://studio.twitter.com"" rel=""nofo...",سبقتهم دموعهم.. لاجئون أوكرانيون على الحدود ال...,None,u2443666806
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,False,"{'retweet_count': 327, 'reply_count': None, 'l...",None,None,"<a href=""http://twitter.com/download/android"" ...",RT @franceonu: 🗳️ The @UN General Assembly ado...,None,u3067857869
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,False,"{'retweet_count': 10, 'reply_count': None, 'li...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",RT @CanesTrack: More gold coming back to the 3...,None,u1375007264
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,False,"{'retweet_count': 2088, 'reply_count': None, '...",None,None,"<a href=""http://twitter.com/download/android"" ...",RT @TAEONYSUS_7: MY HOME ♡ (moni + mini + mini...,None,u1397042382701400068
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://mobile.twitter.com"" rel=""nofo...",Product Demo Next Week – Register Today\nSenio...,None,u117514645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",تعريف المماطلة وأسبابها والعواقب التي تضر المص...,None,u311932430
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,True,"{'retweet_count': 72, 'reply_count': None, 'li...",None,None,"<a href=""https://github.com/corbindavenport/to...",Ukraine 🇺🇦 https://t.co/vepN7rH5YU https://t.c...,None,u1057363273832636417
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,False,"{'retweet_count': 1, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",I have no qualms about this. Every day childre...,None,u143608676
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",@Ramahi27 🎉🎉🎉,None,u725629991271186432
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/android"" ...",الله يرحم الثورة 😀 https://t.co/MWHmZAmqeu,None,u373907847

In [108]:
dfLess = dfTweet.drop(columns=['text'])
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,withheld,uid
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,False,"{'retweet_count': 3, 'reply_count': None, 'lik...",None,None,"<a href=""https://studio.twitter.com"" rel=""nofo...",None,u2443666806
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,False,"{'retweet_count': 327, 'reply_count': None, 'l...",None,None,"<a href=""http://twitter.com/download/android"" ...",None,u3067857869
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,False,"{'retweet_count': 10, 'reply_count': None, 'li...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u1375007264
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,False,"{'retweet_count': 2088, 'reply_count': None, '...",None,None,"<a href=""http://twitter.com/download/android"" ...",None,u1397042382701400068
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://mobile.twitter.com"" rel=""nofo...",None,u117514645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",None,u311932430
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,True,"{'retweet_count': 72, 'reply_count': None, 'li...",None,None,"<a href=""https://github.com/corbindavenport/to...",None,u1057363273832636417
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,False,"{'retweet_count': 1, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u143608676
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u725629991271186432
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/android"" ...",None,u373907847

In [109]:
# 添加时间信息、根据日期切片？
import datetime

def calcuTime(dateStr, r):
    date0 = datetime.datetime.strptime(str(dateStr)[:19], '%Y-%m-%d %H:%M:%S')
    date1 = datetime.datetime.strptime('2022-03-16 00:00:00', '%Y-%m-%d %H:%M:%S')
    delta = date1 - date0
    if r == 'days':
        return delta.days
    else:
        return delta.seconds

calcuTime('2021-03-15 20:14:35+00:00', 'days')

365

In [110]:
dfLess['countDays'] = dfLess['created_at'].apply(lambda x: calcuTime(x, 'days'))
dfLess['countSeconds'] = dfLess['created_at'].apply(lambda x: calcuTime(x, 'seconds'))
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,withheld,uid,countDays,countSeconds
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,False,"{'retweet_count': 3, 'reply_count': None, 'lik...",None,None,"<a href=""https://studio.twitter.com"" rel=""nofo...",None,u2443666806,11,48600
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,False,"{'retweet_count': 327, 'reply_count': None, 'l...",None,None,"<a href=""http://twitter.com/download/android"" ...",None,u3067857869,13,20308
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,False,"{'retweet_count': 10, 'reply_count': None, 'li...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u1375007264,17,5413
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,False,"{'retweet_count': 2088, 'reply_count': None, '...",None,None,"<a href=""http://twitter.com/download/android"" ...",None,u1397042382701400068,23,26039
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://mobile.twitter.com"" rel=""nofo...",None,u117514645,1035,37162
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",None,u311932430,20,10741
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,True,"{'retweet_count': 72, 'reply_count': None, 'li...",None,None,"<a href=""https://github.com/corbindavenport/to...",None,u1057363273832636417,24,11326
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,False,"{'retweet_count': 1, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u143608676,11,31526
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u725629991271186432,31,39754
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/android"" ...",None,u373907847,35,37262

In [111]:
dayList = dfLess['countDays'].tolist()
min(dayList), max(dayList)

(1, 5259)

In [112]:
# 拆分数值特征，这个简单点
dfMetrics = pd.json_normalize(dfLess['public_metrics'])
dfMetrics

        retweet_count  reply_count  like_count  quote_count
0                   3          NaN          29          NaN
1                 327          NaN           0          NaN
2                  10          NaN           0          NaN
3                2088          NaN           0          NaN
4                   0          NaN           2          NaN
...               ...          ...         ...          ...
984712              0          NaN           1          NaN
984713             72          NaN         474          NaN
984714              1          NaN           5          NaN
984715              0          NaN           1          NaN
984716              0          NaN           5          NaN

[984717 rows x 4 columns]

In [113]:
#Nan很多，替换为0
dfMetrics = dfMetrics.fillna(0)

In [114]:
newCols = dfMetrics.columns
for col in newCols:
    dfLess[col] = dfMetrics[col]
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,reply_settings,source,withheld,uid,countDays,countSeconds,retweet_count,reply_count,like_count,quote_count
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,...,None,"<a href=""https://studio.twitter.com"" rel=""nofo...",None,u2443666806,11,48600,3,0.0,29,0.0
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,...,None,"<a href=""http://twitter.com/download/android"" ...",None,u3067857869,13,20308,327,0.0,0,0.0
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,...,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u1375007264,17,5413,10,0.0,0,0.0
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,...,None,"<a href=""http://twitter.com/download/android"" ...",None,u1397042382701400068,23,26039,2088,0.0,0,0.0
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,...,None,"<a href=""https://mobile.twitter.com"" rel=""nofo...",None,u117514645,1035,37162,0,0.0,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,...,None,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",None,u311932430,20,10741,0,0.0,1,0.0
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,...,None,"<a href=""https://github.com/corbindavenport/to...",None,u1057363273832636417,24,11326,72,0.0,474,0.0
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,...,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u143608676,11,31526,1,0.0,5,0.0
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,...,None,"<a href=""http://twitter.com/download/iphone"" r...",None,u725629991271186432,31,39754,0,0.0,1,0.0
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,...,None,"<a href=""http://twitter.com/download/android"" ...",None,u373907847,35,37262,0,0.0,5,0.0

In [115]:
dfTweet['tweetLen'] = dfTweet['text'].apply(len)
dfTweet

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,possibly_sensitive,public_metrics,referenced_tweets,reply_settings,source,text,withheld,uid,tweetLen
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,False,"{'retweet_count': 3, 'reply_count': None, 'lik...",None,None,"<a href=""https://studio.twitter.com"" rel=""nofo...",سبقتهم دموعهم.. لاجئون أوكرانيون على الحدود ال...,None,u2443666806,252
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,False,"{'retweet_count': 327, 'reply_count': None, 'l...",None,None,"<a href=""http://twitter.com/download/android"" ...",RT @franceonu: 🗳️ The @UN General Assembly ado...,None,u3067857869,140
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,False,"{'retweet_count': 10, 'reply_count': None, 'li...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",RT @CanesTrack: More gold coming back to the 3...,None,u1375007264,125
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,False,"{'retweet_count': 2088, 'reply_count': None, '...",None,None,"<a href=""http://twitter.com/download/android"" ...",RT @TAEONYSUS_7: MY HOME ♡ (moni + mini + mini...,None,u1397042382701400068,71
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://mobile.twitter.com"" rel=""nofo...",Product Demo Next Week – Register Today\nSenio...,None,u117514645,288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",تعريف المماطلة وأسبابها والعواقب التي تضر المص...,None,u311932430,180
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,True,"{'retweet_count': 72, 'reply_count': None, 'li...",None,None,"<a href=""https://github.com/corbindavenport/to...",Ukraine 🇺🇦 https://t.co/vepN7rH5YU https://t.c...,None,u1057363273832636417,58
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,False,"{'retweet_count': 1, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",I have no qualms about this. Every day childre...,None,u143608676,100
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/iphone"" r...",@Ramahi27 🎉🎉🎉,None,u725629991271186432,13
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,False,"{'retweet_count': 0, 'reply_count': None, 'lik...",None,None,"<a href=""http://twitter.com/download/android"" ...",الله يرحم الثورة 😀 https://t.co/MWHmZAmqeu,None,u373907847,42

In [116]:
dfLess['tweetLen'] = dfTweet['tweetLen']
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,source,withheld,uid,countDays,countSeconds,retweet_count,reply_count,like_count,quote_count,tweetLen
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,...,"<a href=""https://studio.twitter.com"" rel=""nofo...",None,u2443666806,11,48600,3,0.0,29,0.0,252
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,...,"<a href=""http://twitter.com/download/android"" ...",None,u3067857869,13,20308,327,0.0,0,0.0,140
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,...,"<a href=""http://twitter.com/download/iphone"" r...",None,u1375007264,17,5413,10,0.0,0,0.0,125
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,...,"<a href=""http://twitter.com/download/android"" ...",None,u1397042382701400068,23,26039,2088,0.0,0,0.0,71
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,...,"<a href=""https://mobile.twitter.com"" rel=""nofo...",None,u117514645,1035,37162,0,0.0,2,0.0,288
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,...,"<a href=""https://www.sprinklr.com"" rel=""nofoll...",None,u311932430,20,10741,0,0.0,1,0.0,180
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,...,"<a href=""https://github.com/corbindavenport/to...",None,u1057363273832636417,24,11326,72,0.0,474,0.0,58
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,...,"<a href=""http://twitter.com/download/iphone"" r...",None,u143608676,11,31526,1,0.0,5,0.0,100
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,...,"<a href=""http://twitter.com/download/iphone"" r...",None,u725629991271186432,31,39754,0,0.0,1,0.0,13
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,...,"<a href=""http://twitter.com/download/android"" ...",None,u373907847,35,37262,0,0.0,5,0.0,42

In [117]:
dfLess['countMins'] = dfLess['countSeconds'] // 60
dfLess['countHours'] = dfLess['countMins'] // 60
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,uid,countDays,countSeconds,retweet_count,reply_count,like_count,quote_count,tweetLen,countMins,countHours
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,...,u2443666806,11,48600,3,0.0,29,0.0,252,810,13
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,...,u3067857869,13,20308,327,0.0,0,0.0,140,338,5
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,...,u1375007264,17,5413,10,0.0,0,0.0,125,90,1
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,...,u1397042382701400068,23,26039,2088,0.0,0,0.0,71,433,7
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,...,u117514645,1035,37162,0,0.0,2,0.0,288,619,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,...,u311932430,20,10741,0,0.0,1,0.0,180,179,2
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,...,u1057363273832636417,24,11326,72,0.0,474,0.0,58,188,3
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,...,u143608676,11,31526,1,0.0,5,0.0,100,525,8
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,...,u725629991271186432,31,39754,0,0.0,1,0.0,13,662,11
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,...,u373907847,35,37262,0,0.0,5,0.0,42,621,10

In [118]:
langList = dfLess['lang'].tolist()
len(set(langList))

54

In [119]:
langMap = {lang: i for i, lang in enumerate(set(langList))}

In [120]:
dfLess['langMap'] = dfLess['lang'].map(langMap)
dfLess['langMap']

0         42
1         20
2         20
3         22
4         20
          ..
984712    42
984713    20
984714    20
984715    37
984716    42
Name: langMap, Length: 984717, dtype: int64

In [121]:
dfEntities = pd.json_normalize(dfLess['entities'])

In [122]:
# 涉及list的字段添加长度的数量信息
calcuCols = ['hashtags', 'user_mentions', 'urls', 'media']
for col in calcuCols:
    dfEntities[col] = dfEntities[col].fillna('')
    dfLess[col + '_num'] = dfEntities[col].apply(len)
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,like_count,quote_count,tweetLen,countMins,countHours,langMap,hashtags_num,user_mentions_num,urls_num,media_num
0,None,2443666806,None,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",None,t1499693636107190272,NaN,ar,...,29,0.0,252,810,13,42,3,0,1,1
1,None,3067857869,None,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",None,t1499087527193583627,NaN,en,...,0,0.0,140,338,5,20,1,2,0,0
2,None,1375007264,None,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1497700449411076100,NaN,en,...,0,0.0,125,90,1,20,0,2,0,1
3,None,1397042382701400068,None,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495439610297843713,NaN,et,...,0,0.0,71,433,7,22,0,1,0,1
4,None,117514645,None,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",None,t1128656436291153921,NaN,en,...,2,0.0,288,619,10,20,2,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,None,311932430,None,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",None,t1496590935957901315,NaN,ar,...,1,0.0,180,179,2,42,3,0,1,1
984713,None,1057363273832636417,None,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1495138932740268032,NaN,en,...,474,0.0,58,188,3,20,0,0,1,1
984714,None,143608676,None,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1499765247971840004,NaN,en,...,5,0.0,100,525,8,20,0,0,1,0
984715,None,725629991271186432,None,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1492482983172919296,215002474.0,und,...,1,0.0,13,662,11,37,0,1,0,0
984716,None,373907847,None,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",None,t1491043883241062404,NaN,ar,...,5,0.0,42,621,10,42,0,0,1,0

In [123]:
# 基本确定所选的数值特征
numCols = list(newCols) + [col + '_num' for col in list(calcuCols)] + \
            ['tweetLen', 'countMins', 'countHours', 'langMap']
numCols

['retweet_count',
 'reply_count',
 'like_count',
 'quote_count',
 'hashtags_num',
 'user_mentions_num',
 'urls_num',
 'media_num',
 'tweetLen',
 'countMins',
 'countHours',
 'langMap']

In [124]:
dfLess[numCols]

,retweet_count,reply_count,like_count,quote_count,hashtags_num,user_mentions_num,urls_num,media_num,tweetLen,countMins,countHours,langMap
0,3,0.0,29,0.0,3,0,1,1,252,810,13,42
1,327,0.0,0,0.0,1,2,0,0,140,338,5,20
2,10,0.0,0,0.0,0,2,0,1,125,90,1,20
3,2088,0.0,0,0.0,0,1,0,1,71,433,7,22
4,0,0.0,2,0.0,2,0,1,1,288,619,10,20
...,...,...,...,...,...,...,...,...,...,...,...,...
984712,0,0.0,1,0.0,3,0,1,1,180,179,2,42
984713,72,0.0,474,0.0,0,0,1,1,58,188,3,20
984714,1,0.0,5,0.0,0,0,1,0,100,525,8,20
984715,0,0.0,1,0.0,0,1,0,0,13,662,11,37
984716,0,0.0,5,0.0,0,0,1,0,42,621,10,42

In [125]:
import torch

tweet_num_properties = torch.tensor(dfLess[numCols].values, dtype=int)

In [126]:
torch.save(tweet_num_properties, partPath + 'tweet_num_properties.pt')

In [127]:
# 处理得到类型特征
typeList = []
dfLess.columns

Index(['attachments', 'author_id', 'context_annotations', 'conversation_id',
       'created_at', 'entities', 'geo', 'id', 'in_reply_to_user_id', 'lang',
       'possibly_sensitive', 'public_metrics', 'referenced_tweets',
       'reply_settings', 'source', 'withheld', 'uid', 'countDays',
       'countSeconds', 'retweet_count', 'reply_count', 'like_count',
       'quote_count', 'tweetLen', 'countMins', 'countHours', 'langMap',
       'hashtags_num', 'user_mentions_num', 'urls_num', 'media_num'],
      dtype='object')

In [128]:
import numpy as np
dfLess = dfLess.fillna(np.nan)

In [129]:
originCols = ['attachments', 'context_annotations', 'conversation_id', 'entities', 'geo', 'in_reply_to_user_id', 
             'possibly_sensitive', 'referenced_tweets', 'reply_settings', 'source', 'withheld']

for col in originCols:
    dfLess[col + '_bool'] = dfLess[col].fillna(False).astype(bool).astype(int)
    typeList.append(col + '_bool')
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,context_annotations_bool,conversation_id_bool,entities_bool,geo_bool,in_reply_to_user_id_bool,possibly_sensitive_bool,referenced_tweets_bool,reply_settings_bool,source_bool,withheld_bool
0,NaN,2443666806,NaN,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",NaN,t1499693636107190272,NaN,ar,...,0,1,1,0,0,0,0,0,1,0
1,NaN,3067857869,NaN,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",NaN,t1499087527193583627,NaN,en,...,0,1,1,0,0,0,0,0,1,0
2,NaN,1375007264,NaN,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1497700449411076100,NaN,en,...,0,1,1,0,0,0,0,0,1,0
3,NaN,1397042382701400068,NaN,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1495439610297843713,NaN,et,...,0,1,1,0,0,0,0,0,1,0
4,NaN,117514645,NaN,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",NaN,t1128656436291153921,NaN,en,...,0,1,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,NaN,311932430,NaN,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",NaN,t1496590935957901315,NaN,ar,...,0,1,1,0,0,0,0,0,1,0
984713,NaN,1057363273832636417,NaN,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1495138932740268032,NaN,en,...,0,1,1,0,0,1,0,0,1,0
984714,NaN,143608676,NaN,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1499765247971840004,NaN,en,...,0,1,1,0,0,0,0,0,1,0
984715,NaN,725629991271186432,NaN,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1492482983172919296,215002474.0,und,...,0,1,1,0,1,0,0,0,1,0
984716,NaN,373907847,NaN,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1491043883241062404,NaN,ar,...,0,1,1,0,0,0,0,0,1,0

In [130]:
typeEntities = ['mentions', 'annotations', 'cashtags']
for col in typeEntities:
    typeList.append(col + '_bool')
    dfLess[col + '_bool'] = dfEntities[col].fillna(False).astype(bool).astype(int)
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,geo_bool,in_reply_to_user_id_bool,possibly_sensitive_bool,referenced_tweets_bool,reply_settings_bool,source_bool,withheld_bool,mentions_bool,annotations_bool,cashtags_bool
0,NaN,2443666806,NaN,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",NaN,t1499693636107190272,NaN,ar,...,0,0,0,0,0,1,0,0,0,0
1,NaN,3067857869,NaN,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",NaN,t1499087527193583627,NaN,en,...,0,0,0,0,0,1,0,0,0,0
2,NaN,1375007264,NaN,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1497700449411076100,NaN,en,...,0,0,0,0,0,1,0,0,0,0
3,NaN,1397042382701400068,NaN,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1495439610297843713,NaN,et,...,0,0,0,0,0,1,0,0,0,0
4,NaN,117514645,NaN,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",NaN,t1128656436291153921,NaN,en,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,NaN,311932430,NaN,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",NaN,t1496590935957901315,NaN,ar,...,0,0,0,0,0,1,0,0,0,0
984713,NaN,1057363273832636417,NaN,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1495138932740268032,NaN,en,...,0,0,1,0,0,1,0,0,0,0
984714,NaN,143608676,NaN,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1499765247971840004,NaN,en,...,0,0,0,0,0,1,0,0,0,0
984715,NaN,725629991271186432,NaN,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1492482983172919296,215002474.0,und,...,0,1,0,0,0,1,0,0,0,0
984716,NaN,373907847,NaN,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1491043883241062404,NaN,ar,...,0,0,0,0,0,1,0,0,0,0

In [131]:
typeList

['attachments_bool',
 'context_annotations_bool',
 'conversation_id_bool',
 'entities_bool',
 'geo_bool',
 'in_reply_to_user_id_bool',
 'possibly_sensitive_bool',
 'referenced_tweets_bool',
 'reply_settings_bool',
 'source_bool',
 'withheld_bool',
 'mentions_bool',
 'annotations_bool',
 'cashtags_bool']

In [132]:
tweet_cat_properties = torch.tensor(dfLess[typeList].values, dtype=int)
tweet_cat_properties

tensor([[0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        ...,
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0]])

In [133]:
tweet_cat_properties.shape

torch.Size([984717, 14])

In [134]:
torch.save(tweet_cat_properties, partPath + 'tweet_cat_properties.pt')

In [136]:
from tqdm import trange
dfList = []
for i in trange(min(dayList), max(dayList) + 1):
    dfDay = dfLess.loc[dfLess['countDays'] == i]
    dfList.append(dfDay)

100%|███████████████████████████| 5259/5259 [00:07<00:00, 709.10it/s]

In [137]:
dfDaily = dfList
df10Days = []
min(dayList), max(dayList)

(1, 5259)

In [138]:
df10Days = []
for i in trange(0, 550):
    df10Day = dfLess.loc[(dfLess['countDays'] > i * 10 + 1) & (dfLess['countDays'] < i * 10 + 10)]
    df10Days.append(df10Day)

100%|█████████████████████████████| 550/550 [00:01<00:00, 423.31it/s]

In [139]:
df20Days = []
for i in trange(0, 275):
    df20Day = dfLess.loc[(dfLess['countDays'] > i * 20 + 1) & (dfLess['countDays'] < i * 20 + 20)]
    df20Days.append(df20Day)

100%|█████████████████████████████| 275/275 [00:01<00:00, 210.96it/s]

In [140]:
df50Days = []
for i in trange(0, 100):
    df50Day = dfLess.loc[(dfLess['countDays'] > i * 50 + 1) & (dfLess['countDays'] < i * 50 + 50)]
    df50Days.append(df50Day)

100%|█████████████████████████████| 100/100 [00:00<00:00, 129.36it/s]

In [142]:
dfUserPart

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld
0,2016-09-02 17:13:51+00:00,‏‏‏Abdelwahed Wajih\nعبدالواحد وجيه,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u771758047412748288,None,عبد الواحد وجيه,NaN,https://pbs.twimg.com/profile_images/771764768...,False,"{'followers_count': 2461, 'following_count': 2...",https://t.co/Wev6rydYcI,Wajihabdelwahd0,False,None
1,2009-10-29 08:21:28+00:00,Try my best in all my way to life happily..,None,u86020763,Indonesia,bernardinus,NaN,https://pbs.twimg.com/profile_images/349683458...,False,"{'followers_count': 93, 'following_count': 98,...",,Nduzzt,False,None
2,2018-06-06 19:11:31+00:00,waiting......2022⭐⭐,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1004440668763230210,"El Qaliobia, Egypt",Alhassan,NaN,https://pbs.twimg.com/profile_images/145774969...,False,"{'followers_count': 61, 'following_count': 139...",https://t.co/yuALOjMusA,Alhassa13553164,False,None
3,2014-05-25 14:02:22+00:00,#Bugdroidy #FCIS #Barca,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u2522772534,"Cairo, Egypt",khaled sherif,NaN,https://pbs.twimg.com/profile_images/123885339...,False,"{'followers_count': 287, 'following_count': 31...",https://t.co/0omT0uNzyZ,Meslmawy,False,None
4,2021-03-25 15:48:41+00:00,رب الخير لا ياتى إلا بالخير 🖤,None,u1375112149157216258,None,Nada Abd Alrhman,NaN,https://pbs.twimg.com/profile_images/145660076...,False,"{'followers_count': 39, 'following_count': 141...",,NadaAbdAlrhman3,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8689,2020-05-04 19:20:34+00:00,"egyptian illustrator, comic artist, and magica...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1257389639318585345,20 | she/her,✨Nour T✨ COMMISSIONS OPEN,1.428708e+18,https://pbs.twimg.com/profile_images/147849174...,False,"{'followers_count': 1773, 'following_count': 1...",https://t.co/SAFo4cnBOF,nourtarts,False,None
8690,2020-05-18 02:15:44+00:00,irgendwie irgendwo irgendwann.,None,u1262205160983605250,None,Dwight,NaN,https://pbs.twimg.com/profile_images/136715285...,False,"{'followers_count': 5542, 'following_count': 4...",,dewheit,False,None
8691,2011-10-26 19:01:06+00:00,‏‏الراعي الرسمي لتايم لاين الانمي,None,u398927679,Laugh Tale,الكايزوكو اوني والناكاما بتوعه 🤓,1.231680e+18,https://pbs.twimg.com/profile_images/148066499...,False,"{'followers_count': 3544, 'following_count': 2...",,_AhmedYehya_,False,None
8692,2008-05-20 16:07:04+00:00,"Founder and CEO, 👕🚀\nSports and Gaming\n\nForm...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u14846901,"Dallas, TX",Chris Chaney marcaurel.eth 🇩🇪🇺🇸,NaN,https://pbs.twimg.com/profile_images/126828321...,False,"{'followers_count': 1720, 'following_count': 7...",https://t.co/VGxZ1Wvm5g,chrischaney,False,None
8693,2009-03-25 12:57:54+00:00,"Marvel comics writer: X-FACTOR, GWENPOOL STRIK...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u26490474,"the boneyard, krakoa",Leah Williams,NaN,https://pbs.twimg.com/profile_images/882723937...,False,"{'followers_count': 23119, 'following_count': ...",https://t.co/zk3zXHEC5i,mymonsterischic,False,None

In [144]:
userList = dfUserPart['id'].tolist()
userList[-1]

'u26490474'

In [145]:
userMap = {uid: i for i, uid in enumerate(userList)}
userMap[userList[-1]]

8693

In [146]:
dfLess['uidMap'] = dfLess['uid'].map(userMap)
dfLess

,attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,...,in_reply_to_user_id_bool,possibly_sensitive_bool,referenced_tweets_bool,reply_settings_bool,source_bool,withheld_bool,mentions_bool,annotations_bool,cashtags_bool,uidMap
0,NaN,2443666806,NaN,1499693636107190272,2022-03-04 10:30:00+00:00,"{'hashtags': [{'text': 'روسيا', 'indices': [10...",NaN,t1499693636107190272,NaN,ar,...,0,0,0,0,1,0,0,0,0,1813
1,NaN,3067857869,NaN,1499087527193583627,2022-03-02 18:21:32+00:00,"{'hashtags': [{'text': 'Ukraine', 'indices': [...",NaN,t1499087527193583627,NaN,en,...,0,0,0,0,1,0,0,0,0,3388
2,NaN,1375007264,NaN,1497700449411076100,2022-02-26 22:29:47+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1497700449411076100,NaN,en,...,0,0,0,0,1,0,0,0,0,6080
3,NaN,1397042382701400068,NaN,1495439610297843713,2022-02-20 16:46:01+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1495439610297843713,NaN,et,...,0,0,0,0,1,0,0,0,0,1673
4,NaN,117514645,NaN,1128656436291153921,2019-05-15 13:40:38+00:00,"{'hashtags': [{'text': 'Engineer', 'indices': ...",NaN,t1128656436291153921,NaN,en,...,0,0,0,0,1,0,0,0,0,6173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984712,NaN,311932430,NaN,1496590935957901315,2022-02-23 21:00:59+00:00,"{'hashtags': [{'text': 'يلا_بنات', 'indices': ...",NaN,t1496590935957901315,NaN,ar,...,0,0,0,0,1,0,0,0,0,655
984713,NaN,1057363273832636417,NaN,1495138932740268032,2022-02-19 20:51:14+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1495138932740268032,NaN,en,...,0,1,0,0,1,0,0,0,0,2570
984714,NaN,143608676,NaN,1499765247971840004,2022-03-04 15:14:34+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1499765247971840004,NaN,en,...,0,0,0,0,1,0,0,0,0,3678
984715,NaN,725629991271186432,NaN,1492482983172919296,2022-02-12 12:57:26+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1492482983172919296,215002474.0,und,...,1,0,0,0,1,0,0,0,0,7253
984716,NaN,373907847,NaN,1491043883241062404,2022-02-08 13:38:58+00:00,"{'hashtags': [], 'symbols': [], 'user_mentions...",NaN,t1491043883241062404,NaN,ar,...,0,0,0,0,1,0,0,0,0,189

In [147]:
remainCols = ['id', 'uid', 'uidMap', 'countDays']
dfLess[remainCols].to_csv(partPath + 'tweetMinCols.csv', index=False)

In [148]:
dfMin = pd.read_csv(partPath + 'tweetMinCols.csv')
dfMin

                          id                   uid  uidMap  countDays
0       t1499693636107190272           u2443666806    1813         11
1       t1499087527193583627           u3067857869    3388         13
2       t1497700449411076100           u1375007264    6080         17
3       t1495439610297843713  u1397042382701400068    1673         23
4       t1128656436291153921            u117514645    6173       1035
...                      ...                   ...     ...        ...
984712  t1496590935957901315            u311932430     655         20
984713  t1495138932740268032  u1057363273832636417    2570         24
984714  t1499765247971840004            u143608676    3678         11
984715  t1492482983172919296   u725629991271186432    7253         31
984716  t1491043883241062404            u373907847     189         35

[984717 rows x 4 columns]

In [150]:
type(lovainCom)

list

In [151]:
userComs = list([list(com) for com in lovainCom])
userComs[:10]

[[1,
  262148,
  524296,
  524297,
  262160,
  22,
  23,
  262168,
  25,
  524318,
  524321,
  524322,
  262179,
  37,
  38,
  39,
  45,
  524333,
  262193,
  262196,
  524344,
  262201,
  262202,
  524348,
  60,
  262207,
  262210,
  524355,
  524357,
  71,
  524361,
  73,
  262218,
  74,
  77,
  524365,
  79,
  262221,
  262225,
  262226,
  524370,
  88,
  89,
  93,
  262238,
  524381,
  103,
  262250,
  109,
  262254,
  524403,
  121,
  262266,
  122,
  262268,
  524411,
  262270,
  262269,
  262265,
  524418,
  524422,
  262278,
  524424,
  137,
  524426,
  262283,
  262284,
  524428,
  524430,
  524431,
  262289,
  146,
  262291,
  524436,
  262290,
  262294,
  262295,
  524434,
  262297,
  524442,
  262298,
  524438,
  262301,
  262302,
  161,
  524452,
  262310,
  262311,
  262312,
  262314,
  262316,
  524463,
  524464,
  524466,
  524468,
  524469,
  262324,
  524471,
  187,
  190,
  262335,
  262341,
  524490,
  262346,
  524492,
  524499,
  262355,
  213,
  262357,
  262359,
  216,
  524505,
  217,
  219,
  524507,
  218,
  262367,
  262368,
  225,
  262373,
  262376,
  524522,
  235,
  524525,
  262383,
  524530,
  262389,
  246,
  262392,
  262393,
  262394,
  251,
  252,
  524543,
  259,
  262404,
  262,
  265,
  262412,
  269,
  262415,
  524559,
  262417,
  273,
  524562,
  524565,
  524567,
  262427,
  284,
  288,
  524580,
  297,
  262453,
  524597,
  313,
  524602,
  262459,
  262465,
  524610,
  323,
  325,
  262472,
  262475,
  262476,
  262477,
  262478,
  337,
  524626,
  524631,
  262488,
  262491,
  524635,
  524639,
  524641,
  262497,
  262499,
  524644,
  357,
  524646,
  524647,
  262505,
  262510,
  367,
  524658,
  262516,
  524663,
  376,
  524665,
  378,
  524670,
  387,
  262534,
  524679,
  524680,
  524683,
  262542,
  399,
  262544,
  524688,
  524690,
  262549,
  524694,
  262550,
  408,
  405,
  410,
  262556,
  412,
  524705,
  262562,
  262564,
  262567,
  424,
  262570,
  262571,
  524717,
  524719,
  433,
  524722,
  524723,
  524721,
  262580,
  524726,
  262582,
  524732,
  524734,
  448,
  524738,
  262595,
  452,
  262598,
  262607,
  524751,
  262611,
  524756,
  471,
  524759,
  524761,
  262618,
  524763,
  475,
  476,
  262620,
  262622,
  480,
  262621,
  482,
  524770,
  484,
  262628,
  262630,
  524776,
  524777,
  262635,
  492,
  262637,
  262636,
  262638,
  497,
  524791,
  503,
  524794,
  524795,
  508,
  524797,
  524799,
  262658,
  524802,
  519,
  262664,
  262663,
  522,
  262667,
  523,
  262671,
  532,
  262676,
  533,
  524821,
  524824,
  524826,
  262682,
  262688,
  548,
  262693,
  262695,
  552,
  524841,
  556,
  564,
  524853,
  524855,
  262711,
  524859,
  262717,
  262718,
  524863,
  524873,
  524874,
  586,
  591,
  262736,
  592,
  262746,
  608,
  610,
  524899,
  524900,
  615,
  524907,
  620,
  524908,
  622,
  262769,
  628,
  262773,
  524918,
  524920,
  524921,
  633,
  262783,
  641,
  524931,
  646,
  524935,
  262791,
  262792,
  262793,
  262795,
  652,
  653,
  262798,
  657,
  262802,
  658,
  524949,
  262806,
  664,
  524954,
  262816,
  675,
  524963,
  262822,
  524967,
  681,
  524970,
  524972,
  684,
  524975,
  524979,
  262837,
  262839,
  524987,
  524988,
  524991,
  262848,
  524992,
  524993,
  524994,
  708,
  262854,
  711,
  525000,
  714,
  262861,
  718,
  720,
  262869,
  728,
  262874,
  733,
  525021,
  262878,
  525027,
  739,
  525030,
  743,
  525035,
  525036,
  525038,
  525041,
  754,
  525044,
  262902,
  764,
  765,
  262916,
  262921,
  778,
  525068,
  262924,
  525070,
  525069,
  525076,
  525077,
  525078,
  262934,
  262938,
  525084,
  262940,
  799,
  801,
  262946,
  804,
  262950,
  262953,
  809,
  811,
  525104,
  525107,
  823,
  824,
  525113,
  826,
  525115,
  825,
  831,
  262977,
  833,
  836,
  525126,
  262983,
  262984,
  525128,
  842,
  838,
  844,
  525133,
  846,
  525134,
  840,
  849,
  525138,
  851,
  262997,
  525142,
  859,
  525150,
  863,
  263006,
  865,
  525155,
  263011,
  263016,
  525162,
  263020,
  525167,
  263024,
  884,
  885,
  525174,
  263029,
  525176,
  525178,
  263036,
  525180,
  525186,
  525188,
  263044,
  525191,
  525193,
  263051,
  907,
  909,
  263055,
  911,
  913,
  263060,
  263061,
  918,
  920,
  525208,
  263066,
  923,
  525209,
  925,
  525215,
  927,
  929,
  928,
  932,
  263076,
  936,
  938,
  525228,
  525229,
  525230,
  942,
  944,
  525237,
  263093,
  263097,
  955,
  525244,
  525245,
  959,
  525249,
  962,
  963,
  525253,
  263109,
  525255,
  525256,
  973,
  975,
  979,
  525269,
  984,
  987,
  263132,
  525276,
  263131,
  525279,
  525282,
  263138,
  263146,
  1007,
  1013,
  1019,
  263165,
  525310,
  1022,
  525312,
  1025,
  263170,
  1023,
  1031,
  525320,
  1033,
  263177,
  525323,
  525330,
  263187,
  1044,
  525333,
  263191,
  1048,
  1049,
  263193,
  1052,
  263197,
  263196,
  525343,
  525344,
  263198,
  263202,
  1060,
  525348,
  1062,
  1066,
  525359,
  1073,
  263219,
  1079,
  263223,
  525367,
  263227,
  525371,
  1085,
  1089,
  263238,
  263239,
  1096,
  263241,
  263242,
  525386,
  525388,
  525393,
  263256,
  525402,
  1118,
  263264,
  1121,
  1122,
  263269,
  525414,
  1127,
  263276,
  525421,
  1135,
  263280,
  263284,
  1141,
  263285,
  263288,
  263289,
  1149,
  1155,
  263301,
  525445,
  263304,
  525449,
  263306,
  263307,
  525457,
  1176,
  525465,
  525466,
  1179,
  1180,
  1181,
  525474,
  525479,
  525481,
  1193,
  263339,
  1198,
  263343,
  525492,
  263349,
  1209,
  1211,
  263356,
  525504,
  263360,
  525506,
  263363,
  1220,
  1223,
  525512,
  263370,
  525514,
  263375,
  263376,
  525521,
  263379,
  1237,
  1238,
  263381,
  525528,
  525529,
  525530,
  1245,
  263390,
  1247,
  1246,
  525536,
  1252,
  1254,
  525546,
  263406,
  525551,
  1265,
  263412,
  1270,
  525561,
  1274,
  525562,
  1276,
  1275,
  525563,
  525567,
  1283,
  263427,
  1285,
  1287,
  263433,
  525578,
  263435,
  263434,
  1296,
  525586,
  1300,
  263450,
  525595,
  525596,
  525603,
  1317,
  1320,
  525608,
  525610,
  1327,
  525615,
  1328,
  1332,
  525621,
  263477,
  1335,
  263482,
  1338,
  1340,
  525628,
  525630,
  1343,
  263487,
  1347,
  1348,
  525636,
  263494,
  1350,
  263496,
  525641,
  263499,
  1356,
  263506,
  263508,
  525657,
  1369,
  1371,
  263515,
  525661,
  1373,
  525664,
  263521,
  525666,
  525667,
  525670,
  525674,
  1387,
  1388,
  263533,
  263534,
  1392,
  1394,
  263542,
  525690,
  263548,
  1406,
  1410,
  525698,
  263554,
  525701,
  263560,
  1417,
  263565,
  1424,
  525715,
  1433,
  1434,
  263579,
  525725,
  263582,
  1443,
  1444,
  263589,
  263590,
  525734,
  263591,
  1450,
  525744,
  263601,
  1458,
  263600,
  525750,
  1462,
  525752,
  525755,
  263612,
  1473,
  263618,
  1477,
  525767,
  263624,
  525772,
  1486,
  525774,
  263636,
  525781,
  1496,
  263642,
  525787,
  1504,
  1505,
  525794,
  263652,
  525797,
  525802,
  1520,
  525811,
  263670,
  525815,
  525816,
  263676,
  263678,
  1535,
  525825,
  1539,
  525830,
  263686,
  1545,
  263690,
  525837,
  525839,
  1554,
  1556,
  525845,
  1558,
  263701,
  1561,
  263708,
  263710,
  1567,
  263712,
  1569,
  525856,
  525859,
  263716,
  1574,
  525867,
  1582,
  525870,
  263728,
  263730,
  1587,
  1588,
  525880,
  525881,
  263737,
  1595,
  1592,
  263741,
  263749,
  525897,
  263757,
  263758,
  525906,
  1620,
  263765,
  1623,
  1624,
  263769,
  263770,
  525919,
  1632,
  525920,
  525923,
  1637,
  1638,
  1639,
  263784,
  1642,
  263786,
  1648,
  525938,
  263801,
  525951,
  525952,
  1666,
  1668,
  525956,
  263815,
  525959,
  263819,
  525963,
  263821,
  525964,
  525971,
  263828,
  1685,
  263830,
  263835,
  1692,
  1694,
  525987,
  263845,
  1703,
  1705,
  1707,
  1711,
  1713,
  263859,
  526004,
  1717,
  1718,
  1715,
  263870,
  263871,
  263872,
  526014,
  263874,
  526018,
  526019,
  526015,
  1734,
  263878,
  1737,
  526025,
  526027,
  263887,
  263888,
  263889,
  526034,
  263893,
  263894,
  526037,
  1752,
  526043,
  263900,
  526047,
  526048,
  263903,
  263906,
  526055,
  1774,
  526063,
  263918,
  1779,
  526068,
  1780,
  263926,
  1783,
  1788,
  263937,
  1793,
  526083,
  1796,
  263941,
  1797,
  263945,
  1804,
  526095,
  1809,
  1810,
  526098,
  526100,
  1813,
  526106,
  263962,
  526111,
  526112,
  1825,
  526114,
  263973,
  526118,
  526119,
  526120,
  263976,
  1834,
  526123,
  1840,
  263986,
  263990,
  1847,
  1846,
  1850,
  1851,
  263998,
  526148,
  1861,
  264007,
  264008,
  526153,
  1865,
  526157,
  1873,
  526164,
  264021,
  1879,
  526167,
  264023,
  526172,
  526173,
  1887,
  264036,
  264037,
  526184,
  264049,
  264050,
  1906,
  1912,
  1913,
  264058,
  264057,
  264060,
  526205,
  1919,
  264065,
  526210,
  526209,
  1922,
  264068,
  526212,
  264069,
  264075,
  526220,
  264077,
  264076,
  1935,
  1938,
  1947,
  1948,
  264094,
  1951,
  264099,
  526243,
  526244,
  1959,
  264104,
  526249,
  1964,
  526253,
  264110,
  1966,
  526256,
  526257,
  264111,
  1971,
  264116,
  1975,
  1976,
  ...],
 [0,
  393217,
  2,
  262144,
  131076,
  524293,
  5,
  262151,
  131077,
  131072,
  524300,
  393229,
  131087,
  262162,
  524308,
  524310,
  131094,
  524312,
  262169,
  24,
  524315,
  262172,
  393236,
  131102,
  262175,
  131105,
  262178,
  393251,
  524324,
  35,
  393254,
  262183,
  40,
  41,
  524329,
  262187,
  131116,
  44,
  393262,
  47,
  262191,
  50,
  131123,
  524339,
  55,
  524343,
  393272,
  131130,
  393274,
  131132,
  524349,
  524352,
  524353,
  131138,
  67,
  524356,
  262211,
  524358,
  524362,
  524363,
  393293,
  80,
  131152,
  85,
  86,
  262231,
  524375,
  131162,
  524379,
  92,
  262237,
  393310,
  131168,
  393312,
  99,
  100,
  262244,
  524390,
  524391,
  131175,
  131177,
  524397,
  262255,
  116,
  524405,
  524406,
  524410,
  393344,
  131203,
  262276,
  393350,
  262280,
  393352,
  524427,
  131217,
  393365,
  393366,
  393367,
  524441,
  158,
  524447,
  393379,
  262309,
  524453,
  131238,
  393382,
  524457,
  131241,
  524456,
  131239,
  262318,
  524470,
  131258,
  524474,
  188,
  393405,
  131262,
  262333,
  131259,
  524482,
  524483,
  262340,
  393413,
  524487,
  201,
  204,
  524493,
  205,
  393421,
  262354,
  393426,
  262361,
  524510,
  131294,
  393441,
  131298,
  262371,
  262372,
  393444,
  393446,
  262374,
  524520,
  131305,
  233,
  262379,
  131304,
  237,
  131310,
  262380,
  131312,
  241,
  262378,
  524531,
  244,
  131319,
  131320,
  131321,
  393464,
  524539,
  262395,
  131328,
  131331,
  524548,
  262405,
  524550,
  263,
  264,
  131341,
  393486,
  270,
  131346,
  262418,
  131347,
  393493,
  524566,
  279,
  262425,
  131354,
  283,
  262426,
  131357,
  281,
  262431,
  131360,
  262433,
  524577,
  524579,
  131363,
  393509,
  294,
  262439,
  393511,
  131373,
  393518,
  306,
  131381,
  524598,
  393526,
  131384,
  524601,
  393530,
  131386,
  309,
  312,
  262462,
  262463,
  319,
  524609,
  393536,
  320,
  322,
  131401,
  393548,
  524622,
  393551,
  262480,
  336,
  524630,
  524634,
  262494,
  524640,
  131425,
  393572,
  131430,
  262503,
  524648,
  131433,
  393578,
  360,
  262508,
  524653,
  262509,
  393583,
  524655,
  262513,
  393585,
  131443,
  371,
  131437,
  374,
  262520,
  262522,
  382,
  393599,
  131456,
  524673,
  393600,
  393602,
  393604,
  524676,
  390,
  393605,
  393608,
  262536,
  524682,
  398,
  524686,
  131473,
  131474,
  402,
  262548,
  131478,
  262551,
  262554,
  131483,
  393626,
  416,
  131489,
  393635,
  131492,
  524712,
  262572,
  131503,
  393651,
  393654,
  262583,
  524729,
  393658,
  524731,
  393660,
  446,
  393663,
  262594,
  262596,
  393668,
  524740,
  393670,
  455,
  524744,
  393674,
  459,
  262606,
  131536,
  262609,
  393681,
  467,
  393684,
  393689,
  474,
  393691,
  393694,
  524767,
  524768,
  524766,
  393695,
  393704,
  489,
  131561,
  262632,
  494,
  131567,
  262639,
  524783,
  498,
  501,
  524790,
  262647,
  262645,
  524793,
  262650,
  131579,
  262653,
  393726,
  262655,
  393728,
  517,
  524806,
  520,
  131592,
  524810,
  131596,
  525,
  131597,
  524815,
  528,
  262673,
  524813,
  393747,
  131603,
  524822,
  131607,
  262680,
  393755,
  393756,
  524829,
  262686,
  393759,
  524832,
  524833,
  131616,
  262691,
  524836,
  393764,
  393766,
  551,
  131622,
  393763,
  131626,
  131628,
  524844,
  262703,
  262704,
  262707,
  131639,
  393785,
  524858,
  571,
  572,
  393788,
  131647,
  262720,
  131648,
  131650,
  393798,
  262726,
  131658,
  587,
  131660,
  589,
  393806,
  393807,
  393808,
  524877,
  393803,
  393805,
  393812,
  597,
  598,
  262742,
  599,
  524887,
  600,
  393820,
  262750,
  524895,
  131679,
  131681,
  262756,
  131686,
  131690,
  393835,
  524906,
  524909,
  524910,
  131697,
  393842,
  262771,
  131700,
  524917,
  131699,
  627,
  262777,
  131705,
  524923,
  262779,
  637,
  638,
  131709,
  640,
  262786,
  524933,
  393862,
  393863,
  393864,
  649,
  524938,
  131724,
  131725,
  262804,
  524950,
  393879,
  393881,
  667,
  524956,
  669,
  131743,
  131744,
  524959,
  393890,
  262817,
  679,
  524969,
  524971,
  393901,
  688,
  689,
  695,
  131768,
  393914,
  393915,
  131772,
  131774,
  703,
  704,
  262849,
  706,
  262851,
  705,
  131775,
  393928,
  262856,
  393930,
  262862,
  393936,
  393937,
  393938,
  724,
  525013,
  131797,
  393943,
  729,
  525018,
  393945,
  525020,
  525017,
  525022,
  393949,
  736,
  131808,
  525026,
  262883,
  393952,
  525029,
  262885,
  262888,
  525034,
  262892,
  262893,
  131821,
  131823,
  525043,
  262901,
  758,
  393975,
  760,
  131832,
  763,
  262907,
  262909,
  525051,
  768,
  262913,
  131842,
  262919,
  393992,
  131849,
  782,
  525072,
  394001,
  394000,
  787,
  394007,
  262937,
  394010,
  525083,
  262943,
  131872,
  262945,
  525089,
  131875,
  262948,
  525090,
  525094,
  262955,
  525100,
  813,
  525102,
  812,
  131888,
  131889,
  262957,
  131891,
  262964,
  131892,
  525110,
  394039,
  525114,
  394044,
  262975,
  832,
  262976,
  262979,
  525123,
  394056,
  394057,
  262986,
  525131,
  131913,
  845,
  848,
  525140,
  131926,
  525146,
  394079,
  263007,
  525154,
  394083,
  131939,
  870,
  873,
  263019,
  131948,
  525165,
  875,
  263025,
  525170,
  882,
  394100,
  525171,
  394099,
  887,
  525179,
  891,
  525181,
  131970,
  263045,
  394118,
  394119,
  394127,
  131984,
  131985,
  914,
  525202,
  394132,
  525201,
  525200,
  919,
  263064,
  525210,
  263068,
  131996,
  263070,
  525219,
  132006,
  525224,
  525225,
  263083,
  941,
  263086,
  263087,
  394159,
  525233,
  525235,
  132019,
  132021,
  525238,
  263091,
  132024,
  525240,
  394169,
  263096,
  956,
  263101,
  394174,
  952,
  132033,
  263106,
  394179,
  525252,
  132040,
  969,
  974,
  394190,
  394191,
  525267,
  263123,
  394197,
  132053,
  525271,
  263129,
  525274,
  394203,
  132061,
  990,
  394206,
  394205,
  525278,
  132065,
  263133,
  263140,
  525286,
  394215,
  132072,
  1000,
  1002,
  394217,
  525292,
  263149,
  132079,
  263152,
  263153,
  394227,
  132084,
  525302,
  132087,
  132092,
  132096,
  1029,
  394248,
  394249,
  1034,
  132108,
  1039,
  132112,
  263185,
  1040,
  263186,
  525332,
  1045,
  525335,
  263195,
  1053,
  263201,
  525346,
  525345,
  394276,
  263205,
  132135,
  525352,
  394281,
  525354,
  132139,
  132140,
  1072,
  263217,
  394289,
  1075,
  394288,
  394293,
  1078,
  263224,
  394297,
  1082,
  263228,
  525373,
  525374,
  394303,
  1088,
  525377,
  263231,
  525380,
  394309,
  132165,
  394312,
  394314,
  263245,
  525390,
  525391,
  525392,
  263248,
  1106,
  263246,
  1103,
  132181,
  263249,
  1111,
  132184,
  263252,
  1114,
  1115,
  1116,
  525408,
  394337,
  394338,
  394339,
  132194,
  263272,
  132204,
  525422,
  525423,
  132206,
  394356,
  1144,
  525435,
  132220,
  228,
  525438,
  394367,
  263295,
  394370,
  1160,
  525452,
  263309,
  132237,
  263312,
  1169,
  394387,
  525460,
  394392,
  525467,
  525470,
  394399,
  132256,
  1185,
  132259,
  132260,
  525480,
  1192,
  1194,
  525483,
  394412,
  394411,
  1195,
  525487,
  132271,
  263340,
  132274,
  263347,
  1205,
  525495,
  1207,
  132279,
  394428,
  525501,
  394429,
  132291,
  525509,
  394440,
  132297,
  132298,
  525515,
  525513,
  1230,
  1233,
  394450,
  394451,
  263378,
  1235,
  525526,
  394454,
  132313,
  132314,
  263387,
  263388,
  394461,
  263389,
  132317,
  182609,
  525532,
  132322,
  394468,
  1256,
  394472,
  132330,
  132328,
  263404,
  525548,
  525550,
  132335,
  1264,
  1260,
  1266,
  263410,
  1268,
  525556,
  394482,
  525559,
  394487,
  132343,
  394491,
  525564,
  525566,
  263423,
  1280,
  263424,
  394498,
  1278,
  525568,
  132357,
  1286,
  263431,
  525576,
  525577,
  1290,
  263438,
  394512,
  263442,
  132371,
  394515,
  394517,
  130516,
  525591,
  263448,
  394521,
  394518,
  263451,
  1307,
  394524,
  1311,
  132383,
  394528,
  132386,
  132387,
  263459,
  525605,
  132394,
  394543,
  132402,
  394548,
  263479,
  1336,
  1337,
  394554,
  263483,
  263480,
  132413,
  525625,
  1344,
  132418,
  394563,
  525637,
  132422,
  132424,
  394569,
  263498,
  132425,
  1352,
  525645,
  132430,
  132431,
  263502,
  1353,
  394578,
  263500,
  394580,
  132437,
  1366,
  263511,
  132439,
  263513,
  132436,
  1375,
  132450,
  132453,
  132456,
  525677,
  394606,
  525679,
  132466,
  132467,
  132468,
  394613,
  1396,
  1397,
  132472,
  132470,
  263549,
  263550,
  132480,
  394626,
  1411,
  394630,
  263559,
  525703,
  525706,
  263562,
  132494,
  132495,
  263569,
  525714,
  132497,
  525713,
  263574,
  1431,
  132503,
  132505,
  263578,
  525719,
  394652,
  1437,
  525724,
  263584,
  1440,
  1445,
  394664,
  263592,
  525739,
  525741,
  263602,
  263603,
  263606,
  132537,
  263609,
  263611,
  525757,
  525758,
  132544,
  525764,
  525765,
  525766,
  394694,
  132553,
  132555,
  1485,
  1487,
  525775,
  1489,
  132561,
  1493,
  525782,
  525784,
  1497,
  132570,
  1499,
  525788,
  1500,
  132571,
  1498,
  525792,
  263651,
  525796,
  1509,
  132583,
  525799,
  263659,
  525803,
  263660,
  525806,
  525805,
  394737,
  132593,
  132594,
  132597,
  263673,
  394747,
  525820,
  1533,
  525821,
  132607,
  525824,
  263682,
  1538,
  132616,
  132617,
  263689,
  394763,
  132621,
  394766,
  263694,
  394772,
  ...],
 [393216,
  131073,
  3,
  524291,
  524292,
  524295,
  11,
  393228,
  262159,
  131089,
  393235,
  131091,
  262163,
  131095,
  393241,
  524313,
  262171,
  27,
  131101,
  524316,
  131103,
  262180,
  262184,
  262186,
  524332,
  46,
  524335,
  131120,
  48,
  524338,
  51,
  52,
  393266,
  524342,
  262197,
  524345,
  262203,
  262204,
  61,
  524350,
  131139,
  393283,
  70,
  524359,
  131142,
  393289,
  131147,
  131148,
  84,
  393301,
  524374,
  262229,
  262232,
  262230,
  96,
  393315,
  131176,
  524393,
  262251,
  524395,
  262252,
  110,
  524399,
  393328,
  524401,
  393329,
  393334,
  131200,
  393346,
  262274,
  524420,
  393349,
  524421,
  524423,
  262279,
  262277,
  262281,
  262282,
  262285,
  142,
  524433,
  147,
  262292,
  131222,
  131224,
  393369,
  262299,
  131229,
  131230,
  524446,
  262304,
  160,
  524450,
  131234,
  393380,
  131236,
  524455,
  524458,
  131244,
  262319,
  176,
  131248,
  393393,
  524467,
  175,
  262325,
  393398,
  393397,
  179,
  182,
  393395,
  262328,
  262334,
  524479,
  131267,
  524484,
  131270,
  524486,
  524489,
  131274,
  393418,
  393419,
  262349,
  202,
  131279,
  393424,
  393423,
  210,
  524500,
  214,
  215,
  131288,
  393432,
  131290,
  524508,
  220,
  262366,
  131295,
  393440,
  524513,
  262370,
  524514,

In [152]:
with open(partPath + 'lovainCom.json', 'w') as f:
    f.write(json.dumps(userComs))